kind: pipeline
type: docker
name: default

services:
  - name: hello-world
    image: docker.io/kameshsampath/rust-zig-builder:main
    user: root
    environment:
      PORT: 8080
      RUST_LOG: info
    commands:
      - cargo run --target-dir=/tmp/build
    volumes:
      - name: cargo-cache
        path: /usr/local/cargo/registry

steps:
  - name: wait for the service hello-world to be up
    image: alpine
    commands:
      - apk add -U --no-cache curl
      - until curl --output /dev/null --silent --head --fail http://hello-world:8080 ; do sleep 5; done;

  - name: test
    image: docker.io/kameshsampath/rust-zig-builder:main
    pull: if-not-exists
    user: root
    environment:
      SERVICE_URL: "http://hello-world:8080"
    commands:
      - cargo test --target-dir=/tmp/build
    volumes:
      - name: cargo-cache
        path: /usr/local/cargo/registry

  - name: build
    image: docker.io/kameshsampath/rust-zig-builder:main
    pull: if-not-exists
    user: root
    environment:
      # (TODO) - why not able to write to mounted folder
      CARGO_TARGET_DIR: /tmp/build
    commands:
      - task cross
    volumes:
      - name: cargo-cache
        path: /usr/local/cargo/registry
  
  - name: push
    image: thegeeklab/drone-docker-buildx:23
    privileged: true
    settings:
      context: target
      tags: latest
      labels:
       - org.opencontainers.image.source: https://github.com/kameshsampath/rust-hello-world

volumes:
  - name: cargo-cache
    temp: {}