kind: pipeline
type: docker
name: default

# services:
#   - name: hello-world
#     image: ghcr.io/kameshsampath/rust-builder
#     environment:
#       PORT: 8080
#       RUST_LOG: info
#     commands:
#       - cargo run --target-dir=/dist
#     volumes:
#       - name: cargo-cache
#         path: /usr/local/cargo/registry

steps:
  # - name: wait for the service hello-world to be up
  #   image: alpine
  #   commands:
  #     - apk add -U --no-cache curl
  #     - until curl --output /dev/null --silent --head --fail http://hello-world:8080 ; do sleep 5; done;

  # - name: test
  #   image: ghcr.io/kameshsampath/rust-builder
  #   pull: if-not-exists
  #   environment:
  #     SERVICE_URL: "http://hello-world:8080"
  #   commands:
  #     - cargo test --target-dir=/dist
  #   volumes:
  #     - name: cargo-cache
  #       path: /usr/local/cargo/registry

  - name: build
    image: ghcr.io/kameshsampath/rust-builder
    pull: never
    commands:
      - . "$CARGO_HOME/env"
      - cargo clean
      - cargo build --release --target aarch64-unknown-linux-gnu --target-dir=/build
      - cargo build --release --target x86_64-unknown-linux-gnu --target-dir=/build
      - mv /build target
    volumes:
      - name: cargo-cache
        path: /usr/local/cargo/registry
  
  - name: push
    image: thegeeklab/drone-docker-buildx:23
    privileged: true
    settings:
      auto_tag: true
      context: target
