# https://taskfile.dev

version: '3'

dotenv:
  - .env

vars:
  BUILDER: buildx-multi-arch

tasks:
  prepare-buildx:
    desc: prepare the docker buildx environment
    cmds:
      - docker buildx inspect "{{.BUILDER}}" || docker buildx create --name="{{.BUILDER}}" --driver=docker-container --driver-opt=network=host
    silent: true
  clean:
    desc: cleans the target directory
    cmds:
      - cargo clean
    silent: true
  build:
    desc: builds the application for host platform
    cmds:
      - cargo build
    silent: true
  test:
    desc: runs the unit and integration tests
    cmds:
      - cargo test
    silent: true
  image:
    desc: build ad push the image to container registry
    deps:
      - prepare-buildx
    cmds:
      # - docker buildx build --builder="{{.BUILDER}}" -t "{{.PLUGIN_REPO}}" --platform=linux/arm64 --no-cache --platform=linux/amd64 --push -f Dockerfile .
      - docker buildx build --builder="{{.BUILDER}}" -t "{{.PLUGIN_REPO}}" --platform=linux/arm64 --no-cache --load -f Dockerfile .
  ci:
    desc: runs the drone ci build to do cross platform builds
    cmds:
      - drone exec --trusted --env-file=.env
    silent: true